export const PACKAGE_NAME = "@melai/shared";

export { resolveTemplate, templateVariables, MissingTemplateVariableError } from "./template";

export { experimentSpecSchema, type ExperimentSpec, type RunStatus } from "./experiment";

export {
  fixedChunkParamsSchema,
  sentenceChunkParamsSchema,
  chunkingConfigSpecSchema,
  bm25ParamsSchema,
  vectorParamsSchema,
  hybridRrfParamsSchema,
  retrievalConfigSpecSchema,
  retrievalRunSpecSchema,
  type FixedChunkParams,
  type SentenceChunkParams,
  type ChunkingConfigSpec,
  type Bm25Params,
  type VectorParams,
  type HybridRrfParams,
  type RetrievalConfigSpec,
  type RetrievalRunSpec,
} from "./rag";

export {
  evalTargetSchema,
  datasetSpecSchema,
  retrievalCaseSchema,
  generationCaseSchema,
  caseSchemaForTarget,
  addCasesSpecSchema,
  retrievalScorerSpecSchema,
  evalConfigSpecSchema,
  retrievalSubjectSchema,
  evalRunSpecSchema,
  type EvalTarget,
  type DatasetSpec,
  type RetrievalCase,
  type GenerationCase,
  type AddCasesSpec,
  type RetrievalScorerSpec,
  type EvalConfigSpec,
  type RetrievalSubject,
  type EvalRunSpec,
} from "./eval";

export type {
  ProviderKind,
  ModelSummary,
  ProviderHealth,
  ExperimentSummary,
  RunModelInfo,
  RunDetail,
  ExperimentDetail,
  ChunkingStrategy,
  RetrievalMethod,
  DocumentSummary,
  ChunkingConfigSummary,
  ChunkDetail,
  EmbeddingModelSummary,
  RetrievalConfigSummary,
  RetrievalCandidateDto,
  RetrievalResultDetail,
  RetrievalRunDetail,
  RetrievalRunSummary,
  ScorerSpecDto,
  DatasetSummary,
  DatasetCaseDto,
  DatasetDetail,
  EvalConfigSummary,
  EvalScoreDto,
  EvalCaseResultDto,
  EvalRunDetail,
  EvalRunSummary,
} from "./dto";
